"""initial: all tables

Revision ID: 9855a20cc004
Revises: 
Create Date: 2026-04-30 09:15:10.089676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9855a20cc004'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bvid', sa.String(length=20), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('owner_mid', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('part_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_bvid'), 'videos', ['bvid'], unique=False)
    op.create_table('analysis_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('selected_part_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('force_reanalyze', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_user_id'), 'analysis_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_video_id'), 'analysis_tasks', ['video_id'], unique=False)
    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=True),
    sa.Column('default_asr_model', sa.String(length=100), nullable=True),
    sa.Column('default_embedding_model', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_credentials_user_id'), 'api_credentials', ['user_id'], unique=False)
    op.create_table('bilibili_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sessdata_encrypted', sa.Text(), nullable=True),
    sa.Column('bili_jct_encrypted', sa.Text(), nullable=True),
    sa.Column('buvid3_encrypted', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bilibili_credentials_user_id'), 'bilibili_credentials', ['user_id'], unique=False)
    op.create_table('qa_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('selected_part_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_sessions_user_id'), 'qa_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_qa_sessions_video_id'), 'qa_sessions', ['video_id'], unique=False)
    op.create_table('video_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'cid', name='uq_video_part_cid'),
    sa.UniqueConstraint('video_id', 'page_no', name='uq_video_part_page')
    )
    op.create_index(op.f('ix_video_parts_video_id'), 'video_parts', ['video_id'], unique=False)
    op.create_table('video_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('part_overview', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('key_points', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_summaries_video_id'), 'video_summaries', ['video_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_part_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_part_id'], ['video_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_video_part_id'), 'chapters', ['video_part_id'], unique=False)
    op.create_table('export_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('video_part_id', sa.Integer(), nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.ForeignKeyConstraint(['video_part_id'], ['video_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_user_id'), 'export_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_export_records_video_id'), 'export_records', ['video_id'], unique=False)
    op.create_table('part_analysis_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_task_id', sa.Integer(), nullable=False),
    sa.Column('video_part_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('transcript_source', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_task_id'], ['analysis_tasks.id'], ),
    sa.ForeignKeyConstraint(['video_part_id'], ['video_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_analysis_tasks_analysis_task_id'), 'part_analysis_tasks', ['analysis_task_id'], unique=False)
    op.create_index(op.f('ix_part_analysis_tasks_video_part_id'), 'part_analysis_tasks', ['video_part_id'], unique=False)
    op.create_table('part_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_part_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('key_points', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_part_id'], ['video_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_summaries_video_part_id'), 'part_summaries', ['video_part_id'], unique=False)
    op.create_table('qa_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_messages_session_id'), 'qa_messages', ['session_id'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_part_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['video_part_id'], ['video_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_chunks_video_part_id'), 'transcript_chunks', ['video_part_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_part_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_part_id'], ['video_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_video_part_id'), 'transcript_segments', ['video_part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_segments_video_part_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_transcript_chunks_video_part_id'), table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index(op.f('ix_qa_messages_session_id'), table_name='qa_messages')
    op.drop_table('qa_messages')
    op.drop_index(op.f('ix_part_summaries_video_part_id'), table_name='part_summaries')
    op.drop_table('part_summaries')
    op.drop_index(op.f('ix_part_analysis_tasks_video_part_id'), table_name='part_analysis_tasks')
    op.drop_index(op.f('ix_part_analysis_tasks_analysis_task_id'), table_name='part_analysis_tasks')
    op.drop_table('part_analysis_tasks')
    op.drop_index(op.f('ix_export_records_video_id'), table_name='export_records')
    op.drop_index(op.f('ix_export_records_user_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_chapters_video_part_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_video_summaries_video_id'), table_name='video_summaries')
    op.drop_table('video_summaries')
    op.drop_index(op.f('ix_video_parts_video_id'), table_name='video_parts')
    op.drop_table('video_parts')
    op.drop_index(op.f('ix_qa_sessions_video_id'), table_name='qa_sessions')
    op.drop_index(op.f('ix_qa_sessions_user_id'), table_name='qa_sessions')
    op.drop_table('qa_sessions')
    op.drop_index(op.f('ix_bilibili_credentials_user_id'), table_name='bilibili_credentials')
    op.drop_table('bilibili_credentials')
    op.drop_index(op.f('ix_api_credentials_user_id'), table_name='api_credentials')
    op.drop_table('api_credentials')
    op.drop_index(op.f('ix_analysis_tasks_video_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_user_id'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    op.drop_index(op.f('ix_videos_bvid'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
